s = set()
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))
n = input("ENter number: ")
s.add(int(n))

print(s)